; Generated by AutoGUI 2.6.2
; A quick calculator for calculating differences (percent increase/decrease, adding or subtracting a percentage from a number)
; Most useful when converted to an exe.
#SingleInstance Off
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu Tray, Icon, C:\apps\AHK\Scripts\AutoGUI\Icons\Structor.ico

Gui -MaximizeBox +AlwaysOnTop
Gui Font, s16, Calibri
Gui Add, Text, x16 y16 w120 h23 +0x200, First Number
Gui Font
Gui Font, s16, Calibri
Gui Add, Text, x192 y16 w136 h23 +0x200, Second Number
Gui Font
Gui Add, Edit, x-128 y472 w120 h21 +E0x1000
Gui Font, s16, Calibri
Gui Add, Edit, hWndhEdtValue2 vEdtValue2 gpercentDifference x16 y40 w150 h30 +E0x1000
Gui Add, Link, gswap x170 y41 w20 h20 +0x200 -TabStop, <a>⇄</a>
Gui Font
Gui Font, s16, Calibri
Gui Add, Edit, hWndhEdtValue3 vEdtValue3 gpercentDifference x192 y40 w150 h30 +E0x1000
Gui Font
Gui Font, s16, Calibri
Gui Add, Text, x16 y72 w384 h23 +0x200, `% Change relative to First Number
Gui Font
Gui Font, s16, Calibri
Gui Add, Edit, hWndhEdtValue4 vEdtValue4 gvalueFromPercent x16 y96 w324 h30 +E0x1004 -E0x10000
Gui Add, Text, x16 y128 w384 h23 +0x200, `Difference 
Gui Add, Edit, hWndhEdtValue5 vEdtValue5 x16 y155 w324 h30 +E0x1004 -E0x100
Gui Font

Gui Show, w360 h210, Percent Change

GuiControl, Focus, EdtValue2 
Return

GuiEscape:
GuiClose:
    ExitApp
    
percentDifference()
{
    GuiControlGet,EdtValue2 ;first number
    GuiControlGet,EdtValue3 ;second number
    GuiControlGet,focused_control,FocusV
    if(focused_control!="EdtValue4")
    {
        GuiControl,,EdtValue4,% Round((EdtValue2-EdtValue3)/EdtValue2*-100,2)
    }
    GuiControl,,EdtValue5,% EdtValue2-EdtValue3
}
valueFromPercent()
{
    GuiControlGet,EdtValue2 ;first number
    GuiControlGet,EdtValue4 ;percent
    GuiControlGet,focused_control,FocusV
    if(EdtValue2!="" && focused_control="EdtValue4")
    {
        GuiControl,,EdtValue3,% Round(EdtValue2+(EdtValue4/100*EdtValue2),2)
    }
}

swap()
{
    GuiControlGet,tmp1,,EdtValue2 ;first number
    GuiControlGet,tmp2,,EdtValue3 ;second number
    GuiControl,,EdtValue2, % tmp2
    GuiControl,,EdtValue3, % tmp1
}
